export const worldCapitals = [
  "Abu Dhabi", "Accra", "Addis Ababa", "Algiers", "Amman", "Amsterdam", "Ankara", "Antananarivo", "Barcelona",
  "Ashgabat", "Asmara", "Astana", "Asunción", "Athens", "Baghdad", "Baku", "Bali", "Bali near the Beach",
  "Bali on the Beach", "Bamako", "Bangkok",
  "Bangui", "Banjul", "Basseterre", "Beijing", "Beirut", "Belgrade", "Belmopan", "Berlin", "Bern",
  "Bishkek", "Bissau", "Bogotá", "Brasília", "Bratislava", "Brazzaville", "Bridgetown", "Brussels",
  "Bucharest", "Budapest", "Buenos Aires", "Cairo", "Canberra", "Caracas", "Castries", "Chisinau",
  "Colombo", "Conakry", "Copenhagen", "Dakar", "Damascus", "Dhaka", "Dili", "Djibouti", "Dodoma", "Dubai",
  "Doha", "Dublin", "Dushanbe", "Freetown", "Gaborone", "Georgetown", "Guatemala City", "Hanoi",
  "Harare", "Havana", "Helsinki", "In a Beach Club in Bali", "In a Beach Club in Marbella",
  "Islamabad", "Istanbul", "Jakarta", "Jerusalem", "Kabul", "Kampala",
  "Kathmandu", "Khartoum", "Kigali", "Kingston", "Kingstown", "Kinshasa", "Kuala Lumpur", "Kuwait City",
  "Kyiv", "La Paz", "Libreville", "Lilongwe", "Lima", "Lisbon", "Ljubljana", "Lomé", "London",
  "Luanda", "Lusaka", "Luxembourg", "Madrid", "Majuro", "Malabo", "Malé", "Managua", "Manama",
  "Manila", "Maputo", "Marbella", "Marbella near the Beach", "Marbella on the Beach",
  "Maseru", "Mbabane", "Mexico City", "Minsk", "Mogadishu", "Monaco", "Monrovia",
  "Montevideo", "Moroni", "Moscow", "Muscat", "Nairobi", "Nassau", "Naypyidaw", "New Delhi",
  "Niamey", "Nicosia", "Nouakchott", "Nuku'alofa", "Oslo", "Ottawa", "Ouagadougou", "Panama City",
  "Paramaribo", "Paris", "Phnom Penh", "Podgorica", "Port Louis", "Port Moresby", "Port of Spain",
  "Port-au-Prince", "Porto-Novo", "Prague", "Praia", "Pretoria", "Pristina", "Pyongyang", "Quito",
  "Rabat", "Reykjavik", "Riga", "Riyadh", "Rome", "Roseau", "San José", "San Marino", "San Salvador",
  "Sana'a", "Santiago", "Santo Domingo", "São Tomé", "Sarajevo", "Seoul", "Singapore", "Skopje",
  "Sofia", "Stockholm", "Sucre", "Suva", "Taipei", "Tallinn", "Tashkent", "Tbilisi", "Tegucigalpa",
  "Tehran", "Thimphu", "Tirana", "Tokyo", "Tripoli", "Tunis", "Ulaanbaatar", "Vaduz", "Valletta",
  "Vatican City", "Victoria", "Vienna", "Vientiane", "Vilnius", "Warsaw", "Washington D.C.",
  "Wellington", "Windhoek", "Yaoundé", "Yerevan", "Zagreb"
].sort();
